---
title: "Assignment2"
author: "Gaudenzia Genoni"
date: "2024-12-30"
output: pdf_document
---

```{r}
library(sna)
library(ergm)
library(readxl)
```

```{r}
EIES_T2F_n <- read.csv("EIES_T2.csv", row.names=1)
EIES_T2F_n <- EIES_T2F_n > 2 #consider only friends (3) and good friends (4)

EIES_T2F_n<-as.network(EIES_T2F_n, directed=T) #transform into a network object
```

```{r}
Attributes <- read_excel("Data_Gender_3.xlsx")
EIES_T2F_n %v% "Gender"<- Attributes$Gender

plot(EIES_T2F_n)
gplot(EIES_T2F_n, gmode="graph", displaylabels=T, vertex.col=EIES_T2F_n %v% "Gender"*2)
```

###Part 1

#Model 1

```{r}
EIES_Model1<-ergm(EIES_T2F_n ~ edges+mutual
                  +gwidegree(decay=.3, fixed=TRUE) +gwodegree(decay=.3, fixed=TRUE)
                  +dgwesp(type="OTP", decay=.5, fixed=TRUE)
                  +dgwesp(type="ITP", decay=.5, fixed=TRUE),
                  control=control.ergm(seed=102, MCMC.runtime.traceplot=TRUE), 
                  verbose=TRUE)

summary(EIES_Model1)
```

#Part 2

```{r}
EIES_Model2<-ergm(EIES_T2F_n ~ edges+mutual
                  +nodeicov("Gender")+nodeocov("Gender")+nodematch("Gender"), 
                  control=control.ergm(seed=102, MCMC.runtime.traceplot=TRUE), 
                  verbose=TRUE)

summary(EIES_Model2)
```

#Part 3

```{r}
EIES_Model3<-ergm(EIES_T2F_n ~ edges+mutual
                  +gwidegree(decay=.3, fixed=TRUE) +gwodegree(decay=.3, fixed=TRUE)
                  +dgwesp(type="OTP", decay=.5, fixed=TRUE)
                  +dgwesp(type="ITP", decay=.5, fixed=TRUE)
                  +nodeicov("Gender")+nodeocov("Gender")+nodematch("Gender"), 
                  control=control.ergm(seed=102, MCMC.runtime.traceplot=TRUE), 
                  verbose=TRUE)

summary(EIES_Model3)
```

#Present the results in a table

###Part 2

###Part 3

```{r}
set.seed(565)
gof.choices<-control.gof.ergm(nsim=2000, seed = 565)
```


```{r}
#Model 1
EIES_Model1sim2000<-gof(EIES_Model1, 
                        GOF=~model+idegree+odegree+distance+triadcensus, control=gof.choices)
EIES_Model1sim2000$summary.model
```

```{r}
#Model 2
EIES_Model2sim2000<-gof(EIES_Model2, 
                        GOF=~model+idegree+odegree+distance+triadcensus, control=gof.choices)
EIES_Model2sim2000$summary.model
```


```{r}
#Model 3
EIES_Model3sim2000<-gof(EIES_Model3, 
                        GOF=~model+idegree+odegree+distance+triadcensus, control=gof.choices)
EIES_Model3sim2000$summary.model
```

```{r}
hist(EIES_Model3sim2000$sim.model[,1]+.01, nclass=20, main = paste("Histogram of edges"), probability = T, xlab = NA)
abline(v = EIES_Model3sim2000$summary.model[1,1], col = "red", lwd = 3)
abline(v = EIES_Model3sim2000$summary.model[1,3], col = "blue", lwd = 3, lty=2)
```

```{r}
hist(EIES_Model3sim2000$sim.model[,2]+.01, nclass=25, main = paste("Histogram of mutual"), probability = T, xlab = NA)
abline(v = EIES_Model3sim2000$summary.model[2,1], col = "red", lwd = 3)
abline(v = EIES_Model3sim2000$summary.model[2,3], col = "blue", lwd = 3, lty=2)
```

```{r}
hist(EIES_Model3sim2000$sim.model[,3]+.01, nclass=30, main = paste("Histogram of gwideg"), probability = T, xlab = NA)
abline(v = EIES_Model3sim2000$summary.model[3,1], col = "red", lwd = 3)
abline(v = EIES_Model3sim2000$summary.model[3,3], col = "blue", lwd = 3, lty=2)
```

```{r}
hist(EIES_Model3sim2000$sim.model[,4]+.01, nclass=30, main = paste("Histogram of gwodeg"), probability = T, xlab = NA)
abline(v = EIES_Model3sim2000$summary.model[4,1], col = "red", lwd = 3)
abline(v = EIES_Model3sim2000$summary.model[4,3], col = "blue", lwd = 3, lty=2)
```

```{r}
hist(EIES_Model3sim2000$sim.model[,5]+.01, nclass=30, main = paste("Histogram of gwesp.OTP"), probability = T, xlab = NA)
abline(v = EIES_Model3sim2000$summary.model[5,1], col = "red", lwd = 3)
abline(v = EIES_Model3sim2000$summary.model[5,3], col = "blue", lwd = 3, lty=2)
```


```{r}
hist(EIES_Model3sim2000$sim.model[,6]+.01, nclass=30, main = paste("Histogram of gwesp.ITP"), probability = T, xlab = NA)
abline(v = EIES_Model3sim2000$summary.model[6,1], col = "red", lwd = 3)
abline(v = EIES_Model3sim2000$summary.model[6,3], col = "blue", lwd = 3, lty=2)
```


```{r}
hist(EIES_Model3sim2000$sim.model[,7]+.01, nclass=30, main = paste("Histogram of nodeicov.Gender "), probability = T, xlab = NA)
abline(v = EIES_Model3sim2000$summary.model[7,1], col = "red", lwd = 3)
abline(v = EIES_Model3sim2000$summary.model[7,3], col = "blue", lwd = 3, lty=2)
```


```{r}
hist(EIES_Model3sim2000$sim.model[,8]+.01, nclass=30, main = paste("Histogram of nodeocov.Gender "), probability = T, xlab = NA)
abline(v = EIES_Model3sim2000$summary.model[8,1], col = "red", lwd = 3)
abline(v = EIES_Model3sim2000$summary.model[8,3], col = "blue", lwd = 3, lty=2)
```


```{r}
hist(EIES_Model3sim2000$sim.model[,9]+.01, nclass=30, main = paste("Histogram of nodematch.Gender "), probability = T, xlab = NA)
abline(v = EIES_Model3sim2000$summary.model[9,1], col = "red", lwd = 3)
abline(v = EIES_Model3sim2000$summary.model[9,3], col = "blue", lwd = 3, lty=2)
```


```{r}
plot(EIES_Model3sim2000$sim.model[,1], type="l", main = paste("Trace plot for edges"), ylab="", xlab="")
```

```{r}
plot(EIES_Model3sim2000$sim.model[,2], type="l", main = paste("Trace plot for mutual"), ylab="", xlab="")
```

```{r}
plot(EIES_Model3sim2000$sim.model[,3], type="l", main = paste("Trace plot for gwideg"), ylab="", xlab="")
```

```{r}
plot(EIES_Model3sim2000$sim.model[,4], type="l", main = paste("Trace plot for gwodeg"), ylab="", xlab="")
```


```{r}
plot(EIES_Model3sim2000$sim.model[,5], type="l", main = paste("Trace plot for gwesp.OTP"), ylab="", xlab="")
```


```{r}
plot(EIES_Model3sim2000$sim.model[,6], type="l", main = paste("Trace plot for gwesp.ITP"), ylab="", xlab="")
```


```{r}
plot(EIES_Model3sim2000$sim.model[,7], type="l", main = paste("Trace plot for nodeicov.Gender "), ylab="", xlab="")
```


```{r}
plot(EIES_Model3sim2000$sim.model[,8], type="l", main = paste("Trace plot for nodeocov.Gender "), ylab="", xlab="")
```


```{r}
plot(EIES_Model3sim2000$sim.model[,9], type="l", main = paste("Trace plot for nodematch.Gender "), ylab="", xlab="")
```


```{r}
EIES_Model3sim2000
plot(EIES_Model3sim2000)
```

```{r}
boxplot(EIES_Model3sim2000$sim.odeg[,1:11])  # WARNING adjust 1 to 11 if needed
EIES_Model3sim2000$obs.odeg
for (k in 1:16)
{
  hist(EIES_Model3sim2000$sim.triadcensus[,k], main=colnames(EIES_Model3sim2000$sim.triadcensus)[k])
  abline(v = EIES_Model3sim2000$obs.triadcensus[k], col = "blue", lwd = 3, lty=2)
}
EIES_Model3sim2000$obs.triadcensus
```









