---
title: "R Notebook"
output: html_notebook
---

### Assignment 1
## Nodal level analysis

#By Marco Distasio, Alessandra Gandini, Gaudenzia Genoni, Yishak Tadele Nigatu




```{r}
#importing the libraries
library(sna)
library(igraph)
```


```{r}
#loading the dataset
load("Borgatti_Scientists504.RDA")
```

```{r}
social_net <- ifelse(Borgatti_Scientists504$Collaboration > 2, 1, 0)
```

```{r}
# Check symmetry of the adjacency matrix
is_symmetric <- all(social_net == t(social_net))

if (is_symmetric) {
  print("The graph is undirected.")
} else {
  print("The graph is directed.")
}
```


```{r}
attributes <- Borgatti_Scientists504$Attributes
```

```{r}
attributes$Type <- ifelse(attributes$DeptID %in% c(1, 2, 5), 1, 0)
#there are some NAs, but they get assigned to 0
```



1. Part 1

```{r}
par(mar=c(0,0,0,0))
```

```{r}
gplot(social_net, gmode = "graph")
```


2. Part 2

```{r}
node_colors <- ifelse(attributes$Type == 1, "orange", "blue")
```

```{r}
gplot(
  social_net,
  vertex.col = node_colors, # Use the color vector for nodes
  edge.col = "gray",        # Optional: Set edge color
  label.cex = 0.7           # Adjust label size
)
```


3. Part 3

```{r}
# Convert the adjacency matrix to an igraph object
g <- graph_from_adjacency_matrix(social_net, mode = "undirected", diag = FALSE)
```

```{r}
# Degree centrality
degree_centrality <- degree(g, mode = "all")
```


```{r}
# Closeness centrality
closeness_centrality <- closeness(g, normalized = T) #which type of closeness?
#Freeman's closeness with normalization
```


```{r}
top_degree_index <- which.max(degree_centrality)

# Retrieve the actual name of the node
max_node_name <- V(g)$name[top_degree_index]

max_node_info <- subset(attributes, NodeName == max_node_name)

# Get the 'Type' (or any other attribute you need, like 'DeptID')
node_type <- max_node_info$Type

cat("The node with the highest degree centrality is:", max_node_name, "\n")
cat("The highest degree centrality value is:", degree_centrality[max_node_index], "\n")
cat("The type of this node is:", node_type, "\n")
```


```{r}
top_closeness_index  <- which.max(closeness_centrality)

# Retrieve the actual name of the node
max_node_name <- V(g)$name[top_closeness_index]

max_node_info <- subset(attributes, NodeName == max_node_name)

# Get the 'Type' (or any other attribute you need, like 'DeptID')
node_type <- max_node_info$Type

cat("The node with the highest degree centrality is:", max_node_name, "\n")
cat("The highest degree centrality value is:", closeness_centrality[max_node_index], "\n")
cat("The type of this node is:", node_type, "\n")
```


```{r}
# Set default node size and color
node_sizes <- rep(5, vcount(g)) # Default size
node_colors <- ifelse(Borgatti_Scientists504$Attributes$Type == 1, "orange", "blue") # Existing colors

# Highlight the nodes with the highest centrality
node_sizes[top_degree_index] <- 10 # Larger size for highest degree centrality


node_sizes[top_closeness_index] <- 10 # Larger size for highest closeness centrality

gplot(
  social_net,
  vertex.col = node_colors, # Use the enhanced colors
  vertex.cex = node_sizes / 5, # Scale sizes appropriately
  edge.col = "gray",
  label.cex = 0.7
)


```


4. Part 4

```{r}
cor.test(degree_centrality, closeness_centrality)
```


5. Part 5

```{r}
cor.test(degree_centrality, attributes$Type)
```

```{r}
cor.test(closeness_centrality, attributes$Type)
```






